// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgqodhmawzyhhlxzxrog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBncW9kaG1hd3p5aGhseHp4cm9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNzMyMzgsImV4cCI6MjA2NTc0OTIzOH0.CorU0v2GkVIZ_y6IX8X6IyQciW5mHKESZVUS82cWVLY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);